apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: glad2os/patay-development:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-lb
spec:
  selector:
    app: nodejs
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80